spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/huacaoye/spring-cloud-config-repo.git
          username: 543046534@qq.com
          password: angel.123
          search-paths: config-repo/{application}
    bus:
      trace:
        enabled: true
  security:
    user:
      name: admin
      password: candy.123
  rabbitmq:
    host: ${RABBIT_MQ_HOST:172.31.40.7}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:alvin}
    password: ${RABBIT_MQ_PASSWORD:candy.123}
    virtual-host: test
server:
  port: 8764



#需要暴露监控端口给spring boot admin server访问
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
